# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'

pool: AzureBuildScaleSet

steps:
#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.x'
#    addToPath: true
#    architecture: 'x64'
- script: |
    sudo apt-get install -y python3-pip 
    pip3 install build pytest pytest-cov wheel pytest-html pyspark prophecy-build-tool
  env:
    PATH: /home/AzDevOps/.local/bin:$(PATH)
  displayName: 'Install dependencies'
- script: |
    pbt build --path prophecy
  env:
    PATH: /home/AzDevOps/.local/bin:$(PATH)
  displayName: 'PBT build'
- script: |
    pbt test --path prophecy
  displayName: 'PBT test'
  env:
    PATH: /home/AzDevOps/.local/bin:$(PATH)

