on:
  push:
    branches:
      - 'main'

env:
  DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DEV_DATBRICKS_TOKEN }}
  FABRIC_NAME: "HelloDev"

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Install all python dependencies 
      # prophecy-libs not included here because prophecy-build-tool 
      # takes care of it by reading each pipeline's setup.py
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install build pytest wheel pytest-html pyspark prophecy-build-tool
      # Make sure you set the path to match the Project directory
      - name: Run PBT build
        run: pbt build --path prophecy
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
      - name: Archive files for release
        run: |
          tar -zcf helloprophecy-${{steps.tag_version.new_tag}}.tar.gz prophecy
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: helloprophecy-${{steps.tag_version.new_tag}}.tar.gz
          prerelease: true
      - name: Deploy to Databricks
        run:
            pbt deploy --path prophecy
